MvcBiblioteka/Models/Ksiazka.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using Newtonsoft.Json;

namespace MvcBiblioteka.Models
{
    public class Ksiazka
    {
        [JsonProperty(PropertyName="id")]
        public string Id { get; set; }

        [JsonProperty(PropertyName = "tytul")]
        public string Tytul { get; set; }

        [JsonProperty(PropertyName = "autor")]
        public string Autor { get; set; }

        [JsonProperty(PropertyName = "wydawnictwo")]
        public string Wydawnictwo { get; set; }

        [JsonProperty(PropertyName = "miejsceWydania")]
        public string Miejsce_Wydania { get; set; }

        [JsonProperty(PropertyName = "rokWydania")]
        public string Rok_Wydania { get; set; }

        [JsonProperty(PropertyName = "isbn")]
        public string Nr_ISBN { get; set; }

        [JsonProperty(PropertyName = "ilosc")]
        public int Ilosc { get; set; }
    }
}

MvcBiblioteka/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBiblioteka.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

MvcBiblioteka/Controllers/KsiazkaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Net;
using System.Threading.Tasks;
using MvcBiblioteka.Models;

namespace MvcBiblioteka.Controllers
{
    public class KsiazkaController : Controller
    {
        public ActionResult Index()
        {
            var items = DocumentDBRepository<Ksiazka>.GetItems(d => !d.Ilosc.Equals(0));
            return View(items);
        }

        public ActionResult SearchIndex(string autor)
        {
            var items = DocumentDBRepository<Ksiazka>.GetItems(d => !d.Ilosc.Equals(0) && d.Autor == autor);
            return View(items);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Tytul,Autor,Wydawnictwo,Miejsce_Wydania,Rok_Wydania,Nr_ISBN,Ilosc")] Ksiazka ksiazka)
        {
            if (ModelState.IsValid)
            {
                await DocumentDBRepository<Ksiazka>.CreateItemAsync(ksiazka);
                return RedirectToAction("Index");
            }
            return View(ksiazka);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Tytul,Autor,Wydawnictwo,Miejsce_Wydania,Rok_Wydania,Nr_ISBN,Ilosc")] Ksiazka ksiazka)
        {
            if (ModelState.IsValid)
            {
                await DocumentDBRepository<Ksiazka>.UpdateItemAsync(ksiazka.Id, ksiazka);
                return RedirectToAction("Index");
            }

            return View(ksiazka);
        }

        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ksiazka ksiazka = (Ksiazka)DocumentDBRepository<Ksiazka>.GetItem(d => d.Id == id);

            if (ksiazka == null)
            {
                return HttpNotFound();
            }

            return View(ksiazka);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete([Bind(Include = "Id,Tytul,Autor,Wydawnictwo,Miejsce_Wydania,Rok_Wydania,Nr_ISBN,Ilosc")] Ksiazka ksiazka)
        {
            if (ModelState.IsValid)
            {
                await DocumentDBRepository<Ksiazka>.DeleteItemAsync(ksiazka.Id);
                return RedirectToAction("Index");
            }

            return View(ksiazka);
        }

        public ActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ksiazka ksiazka = (Ksiazka)DocumentDBRepository<Ksiazka>.GetItem(d => d.Id == id);

            if (ksiazka == null)
            {
                return HttpNotFound();
            }

            return View(ksiazka);
        }
    }
}

MvcBiblioteka/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>O nas</h1>
</hgroup>

<article>
    <p>
        Zapraszamy do naszej Biblioteki osoby w każdym wieku.
    </p>

    <p>
        Nasze zbiory to książki z ostatniej dekady.
    </p>

    <p>
        U nas znajdziecie "świeżynki", czyli książki, które miały swą premierę w 2015 roku.
    </p>
    <p>
        <h2>Zapraszamy!</h2>
    </p>
</article>

<aside>

    <ul>
        <li>@Html.ActionLink("Strona Główna", "Index", "Ksiazki")</li>
        <li>@Html.ActionLink("Szukaj", "SearchIndex", "Ksiazki")</li>
        <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
    </ul>
</aside>

MvcBiblioteka/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<section class="contact">
    <header>
        <h3>Telefon</h3>
    </header>
    <p>
        <span>22-222-22-22</span>
    </p>
    <p>
        <span>00-000-000-000</span>
    </p>

</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Dział rezerwacji:</span>
        <span><a href="mailto:Support@example.com">Biblioteka@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Adres</h3>
    </header>
    <p>
        ul. Oczytana 5<br />
        00-000, Czytankowo
    </p>
</section>

MvcBiblioteka/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

MvcBiblioteka/Views/Ksiazka/Create.cshtml
@model MvcBiblioteka.Models.Ksiazka

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Ksiazka</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nr_ISBN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nr_ISBN)
            @Html.ValidationMessageFor(model => model.Nr_ISBN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tytul)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tytul)
            @Html.ValidationMessageFor(model => model.Tytul)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Autor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Autor)
            @Html.ValidationMessageFor(model => model.Autor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Wydawnictwo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Wydawnictwo)
            @Html.ValidationMessageFor(model => model.Wydawnictwo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Miejsce_Wydania)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Miejsce_Wydania)
            @Html.ValidationMessageFor(model => model.Miejsce_Wydania)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rok_Wydania)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rok_Wydania)
            @Html.ValidationMessageFor(model => model.Rok_Wydania)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Ilosc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Ilosc)
            @Html.ValidationMessageFor(model => model.Ilosc)
        </div>


        <p>
            <input type="submit" value="Dodaj" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcBiblioteka/Views/Ksiazka/Delete.cshtml
@model MvcBiblioteka.Models.Ksiazka

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Ksiazka</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nr_ISBN)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nr_ISBN)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Tytul)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tytul)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Autor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Autor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Wydawnictwo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Wydawnictwo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Miejsce_Wydania)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Miejsce_Wydania)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rok_Wydania)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rok_Wydania)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Ilosc)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ilosc)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcBiblioteka/Views/Ksiazka/Details.cshtml
@model MvcBiblioteka.Models.Ksiazka

@{
    ViewBag.Title = "Szczegóły";
}

<h2>Szczegóły</h2>

<fieldset>
    <legend>Ksiazka</legend>


    <div class="display-label">
         @Html.DisplayNameFor(model => model.Tytul)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tytul)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Autor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Autor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Wydawnictwo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Wydawnictwo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Miejsce_Wydania)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Miejsce_Wydania)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rok_Wydania)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rok_Wydania)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ilosc)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ilosc)
    </div>
    
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nr_ISBN)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nr_ISBN)
    </div>

</fieldset>
<p>
    @Html.ActionLink("Wróć do listy", "Index")
</p>

MvcBiblioteka/Views/Ksiazka/Edit.cshtml
@model MvcBiblioteka.Models.Ksiazka

@{
    ViewBag.Title = "Rezerwuj";
}

<h2>Edytuj</h2>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Ksiazka</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nr_ISBN)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nr_ISBN)
            @Html.ValidationMessageFor(model => model.Nr_ISBN)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tytul)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tytul)
            @Html.ValidationMessageFor(model => model.Tytul)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Autor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Autor)
            @Html.ValidationMessageFor(model => model.Autor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Wydawnictwo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Wydawnictwo)
            @Html.ValidationMessageFor(model => model.Wydawnictwo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Miejsce_Wydania)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Miejsce_Wydania)
            @Html.ValidationMessageFor(model => model.Miejsce_Wydania)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rok_Wydania)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rok_Wydania)
            @Html.ValidationMessageFor(model => model.Rok_Wydania)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Ilosc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Ilosc)
            @Html.ValidationMessageFor(model => model.Ilosc)
        </div>

        <p>
            <input type="submit" value="Zatwierdź" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Wróć do Listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcBiblioteka/Views/Ksiazka/Index.cshtml
@model IEnumerable<MvcBiblioteka.Models.Ksiazka>

@{
    ViewBag.Title = "Index";
}

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tytul)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wydawnictwo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rok_Wydania)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ilosc)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tytul)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wydawnictwo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rok_Wydania)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ilosc)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.Id })
                @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

MvcBiblioteka/Views/Ksiazka/SearchIndex.cshtml
@model IEnumerable<MvcBiblioteka.Models.Ksiazka>

@{
    ViewBag.Title = "SearchIndex";
}

<h2>Szukaj</h2>
<p>
@using (Html.BeginForm()){    
         <p> Autor:@Html.DropDownList("Autor", "All")<br />  
         <input type="submit" value="Znajdź" /></p> 
        }
</p>

<p></p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tytul)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wydawnictwo)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Miejsce_Wydania)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Rok_Wydania)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nr_ISBN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ilosc)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Rezerwuj)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Tytul)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Wydawnictwo)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Miejsce_Wydania)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Rok_Wydania)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nr_ISBN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ilosc)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Rezerwuj)
        </td>*@
        
    </tr>
}

</table>

MvcBiblioteka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"f4e6dd72-ea14-4044-88fe-10c9aca8d08a"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Biblioteka", "Index", "Ksiazka", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dodaj książkę", "Create", "Ksiazka")</li>
                    <li>@Html.ActionLink("O nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>